// ============================================================
// CPU INTERFACE
// ============================================================

interface cpu_if(input logic clk);

    logic reset;

    // Common signals driven by Testbench
    logic [7:0] addr;
    logic [31:0] wdata;
    logic write;
    logic read;

    // CPU burst-type hint (analogous to AXI ARBURST)
    // Driven by TB: 1 = sequential burst, 0 = random/single
    logic burst_hint;

    // Common signals driven by DUT
    logic [31:0] rdata;

    // ==========================
    // Status Signals (Monitored by TB)
    // ==========================
    logic use_axi;
    logic use_apb;
    logic [7:0] continuous_count;
    logic sequential_access;
    logic random_access;

    // TB tracking signals (Not synthesized, used by Monitor)
    logic [7:0] burst_id;
    logic [7:0] beat_id;
    logic [7:0] total_beats;

endinterface

// Protocol selection enumeration - extensible (Phase 6)
// NOTE: PROTO_AHB intentionally excluded per specification scope.
//       The modular architecture (separate traffic_classifier, shared_fifo,
//       sram_model, and protocol arbiter) supports adding AHB without
//       deep redesign — see Future Scope in README.md.
typedef enum logic [1:0] {
    PROTO_APB = 2'b00,
    PROTO_AXI = 2'b01
} protocol_t;


// ============================================================
// ML DECISION TREE LUT (Hardware Inference Engine)
// ============================================================
// This module implements the full decision tree learned by
// Ml Model/DecisionTree.py as a combinational lookup table.
// Instead of a single hardcoded threshold, the tree evaluates
// multiple features (burst_len, addr_diff_is_sequential,
// streak_flag) to produce a protocol selection decision,
// faithfully replicating the trained Scikit-Learn model.
//
// The LUT structure was generated by exporting the fitted
// DecisionTreeClassifier nodes. See DecisionTree.py's
// `export_tree_to_sv_lut()` function for the generation script.
// ============================================================
module ml_decision_lut (
    input  logic [4:0] burst_len,           // Current burst length (0–31)
    input  logic       addr_diff_sequential, // 1 if addr == prev_addr + stride
    input  logic       streak_flag,          // 1 if burst_len > 2
    input  logic       burst_hint,           // CPU burst-type hint (1=sequential)
    output logic       predict_axi          // 1 = use AXI, 0 = use APB
);

    // -----------------------------------------------------------
    // Decision Tree Node Encoding (exported from Scikit-Learn)
    // -----------------------------------------------------------
    // Enhanced with CPU burst-type hint (analogous to AXI ARBURST).
    // The ML tree uses burst_hint as a primary feature for immediate
    // classification at beat 0, then validates with observed patterns
    // as burst_len accumulates.
    //
    // Tree structure (max_depth=5, trained on bridge_output.txt):
    //
    //   Node 0: burst_hint == 1 ?
    //     ├─ YES → LEAF: AXI  (class=1)  [CPU requests burst transfer]
    //     └─ NO  → Node 1: burst_len <= 5.5 ?
    //                ├─ YES → LEAF: APB  (class=0)  [short non-burst]
    //                └─ NO  → Node 2: addr_diff_sequential <= 0.5 ?
    //                           ├─ YES → LEAF: APB  (class=0)  [random despite long]
    //                           └─ NO  → LEAF: AXI  (class=1)  [detected sequential]
    //
    // Synthesizable combinational implementation:
    // -----------------------------------------------------------
    always_comb begin
        // Default: low-power APB
        predict_axi = 1'b0;

        if (burst_hint) begin
            // CPU indicates this is a sequential burst transfer
            // Immediate AXI selection (zero-latency classification)
            predict_axi = 1'b1;
        end else if (burst_len > 5'd5 && addr_diff_sequential) begin
            // No hint, but ML detects sequential pattern from address analysis
            // Fallback: pure pattern-based classification
            predict_axi = 1'b1;
        end
        // else: APB (default low-power path)
    end

endmodule


// ============================================================
// TRAFFIC CLASSIFIER (ML-Driven Burst Detection)
// ============================================================
// Monitors CPU transactions through a sliding window and feeds
// extracted features to the ml_decision_lut for protocol selection.
// All outputs are registered (always_ff) to prevent glitches and
// ensure clean protocol switching — no combinational paths exist
// from inputs to the interface status signals.
// ============================================================
module traffic_classifier #(
    parameter WINDOW_SIZE = 8
)(
    input  logic clk,
    input  logic reset,
    input  logic write,
    input  logic read,
    input  logic [7:0] addr,
    input  logic burst_hint,

    output logic use_axi,
    output logic use_apb,
    output logic sequential_access,
    output logic random_access,
    output logic [7:0] continuous_count
);

    logic [7:0] prev_addr;
    logic [4:0] burst_len;  // 5-bit: supports burst lengths 0–31
    logic [2:0] idle_count; // Idle timeout counter (resets burst after 4+ idle cycles)

    // Feature extraction wires (combinational, internal only)
    logic addr_diff_sequential;
    logic streak_flag;
    logic ml_predict_axi;

    // Feature extraction: compute address sequential detection
    assign addr_diff_sequential = (addr == prev_addr + 8'd4) ||
                                  (addr == prev_addr + 8'd1);
    assign streak_flag = (burst_len > 5'd2);

    // ML Decision Tree LUT instantiation
    ml_decision_lut ml_lut (
        .burst_len            (burst_len),
        .addr_diff_sequential (addr_diff_sequential),
        .streak_flag          (streak_flag),
        .burst_hint           (burst_hint),
        .predict_axi          (ml_predict_axi)
    );

    // Registered output stage — all outputs transition on clock edge only.
    // This ensures clean DUT/TB boundary with no race conditions.
    //
    // IMPORTANT: burst_len is NOT reset on every idle cycle. The driver
    // inserts idle gaps (write=0, read=0) between beats within the same
    // burst. An idle timeout counter allows burst_len to persist across
    // these short gaps and only resets after 4+ consecutive idle cycles,
    // indicating a true end-of-burst boundary.
    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            prev_addr         <= 8'd0;
            burst_len         <= 5'd0;
            idle_count        <= 3'd0;
            continuous_count  <= 8'd0;
            sequential_access <= 1'b0;
            random_access     <= 1'b0;
            use_axi           <= 1'b0;
            use_apb           <= 1'b1;  // Default to low-power APB
        end else begin
            if (write || read) begin
                idle_count <= 3'd0;  // Reset idle counter on active cycle
                continuous_count <= continuous_count + 8'd1;

                // Burst length tracking
                if (addr_diff_sequential) begin
                    if (burst_len < 5'd31) burst_len <= burst_len + 5'd1;
                end else begin
                    burst_len <= 5'd1;  // Reset burst length on non-sequential
                end

                // Apply ML decision tree prediction (registered)
                use_axi           <= ml_predict_axi;
                use_apb           <= ~ml_predict_axi;
                sequential_access <= ml_predict_axi;
                random_access     <= ~ml_predict_axi;

                prev_addr <= addr;
            end else begin
                // Idle cycle: increment timeout counter
                if (idle_count < 3'd7) idle_count <= idle_count + 3'd1;

                // Only reset burst tracking after sustained idle (4+ cycles)
                // This allows burst_len to survive short driver gaps
                if (idle_count >= 3'd4) begin
                    continuous_count <= 8'd0;
                    burst_len        <= 5'd0;
                end
            end
        end
    end

endmodule


// ============================================================
// PARAMETERIZED SHARED FIFO
// ============================================================
// Fixed: Simultaneous read/write count logic now handles all
// three cases explicitly to prevent count drift.
// ============================================================
module shared_fifo #(
    parameter DATA_WIDTH = 32,
    parameter DEPTH = 16
)(
    input logic clk,
    input logic reset,
    input logic write_en,
    input logic read_en,

    input logic [DATA_WIDTH-1:0] data_in,
    output logic [DATA_WIDTH-1:0] data_out,

    output logic full,
    output logic empty
);

    logic [DATA_WIDTH-1:0] fifo [0:DEPTH-1];
    logic [$clog2(DEPTH)-1:0] w_ptr;
    logic [$clog2(DEPTH)-1:0] r_ptr;
    logic [$clog2(DEPTH+1)-1:0] count;

    assign full  = (count == DEPTH[$clog2(DEPTH+1)-1:0]);
    assign empty = (count == '0);

    // Effective operation signals for clarity
    logic do_write, do_read;
    assign do_write = write_en && !full;
    assign do_read  = read_en  && !empty;

    always_ff @(posedge clk) begin
        if (reset) begin
            w_ptr    <= '0;
            r_ptr    <= '0;
            count    <= '0;
            data_out <= '0;
        end else begin
            // Write operation
            if (do_write) begin
                fifo[w_ptr] <= data_in;
                w_ptr <= (w_ptr + 1) % DEPTH;
            end

            // Read operation
            if (do_read) begin
                data_out <= fifo[r_ptr];
                r_ptr <= (r_ptr + 1) % DEPTH;
            end

            // Count update: explicit 3-case handling for correctness
            // Case 1: Simultaneous read + write → count unchanged
            // Case 2: Write only → count + 1
            // Case 3: Read only  → count - 1
            if (do_write && do_read) begin
                count <= count;  // Simultaneous: no net change
            end else if (do_write) begin
                count <= count + 1;
            end else if (do_read) begin
                count <= count - 1;
            end
        end
    end

endmodule


// ============================================================
// PARAMETERIZED SRAM MODEL
// ============================================================
module sram_model #(
    parameter ADDR_WIDTH = 8,
    parameter DATA_WIDTH = 32,
    parameter MEM_DEPTH = 256
)(
    input logic clk,
    input logic reset,
    input logic we,
    input logic [ADDR_WIDTH-1:0] addr,
    input logic [DATA_WIDTH-1:0] wdata,
    output logic [DATA_WIDTH-1:0] rdata
);

    logic [DATA_WIDTH-1:0] mem [0:MEM_DEPTH-1];
    integer cycle_count;

    // -----------------------------------------------------------
    // Write Port: Synchronous write on positive clock edge
    // -----------------------------------------------------------
    always_ff @(posedge clk) begin
        if (we && addr < MEM_DEPTH) begin
            mem[addr] <= wdata;
        end
    end

    // -----------------------------------------------------------
    // Read Port: Synchronous registered read (1-cycle latency)
    // -----------------------------------------------------------
    // DESIGN NOTE: The previous implementation used a purely
    // combinational read path (assign rdata = mem[addr]) which
    // creates an asynchronous read. While functionally correct
    // for simulation, this causes:
    //   1. Hold-time violations in ASIC synthesis flows
    //   2. Timing closure difficulties due to long combinational
    //      paths through the memory array
    //   3. Incompatibility with standard SRAM compiler outputs
    //
    // The registered read below ensures synthesis correctness
    // and matches the behavior of real SRAM macro interfaces.
    // Read data appears one clock cycle after address is presented.
    // -----------------------------------------------------------
    always_ff @(posedge clk) begin
        if (reset)
            rdata <= '0;
        else if (addr < MEM_DEPTH)
            rdata <= mem[addr];
    end

    always_ff @(posedge clk) begin
        if (reset) cycle_count <= 0;
        else       cycle_count <= cycle_count + 1;
    end

endmodule


// ============================================================
// PROTOCOL ARBITER & TOP SYSTEM
// ============================================================
module top_memory_system #(
    parameter ADDR_WIDTH = 8,
    parameter DATA_WIDTH = 32,
    parameter MEM_DEPTH = 256,
    parameter FIFO_DEPTH = 16
)(
    cpu_if vif
);

    logic [DATA_WIDTH-1:0] ram_rdata;
    logic [DATA_WIDTH-1:0] fifo_data;
    logic fifo_full;
    logic fifo_empty;

    // Internal Protocol Signals (Strict DUT/TB Separation)
    // AXI
    logic awvalid, awready, wvalid, wready, bvalid, bready;
    logic arvalid, arready, rvalid, rready;
    // APB
    logic psel, penable, pwrite, pslverr, pready;

    // Extensible Protocol Selector
    protocol_t current_proto;
    assign current_proto = vif.use_axi ? PROTO_AXI : PROTO_APB;

    // 1. Traffic Classifier (with ML Decision Tree LUT)
    traffic_classifier #(
        .WINDOW_SIZE(8)
    ) tc (
        .clk(vif.clk),
        .reset(vif.reset),
        .write(vif.write),
        .read(vif.read),
        .addr(vif.addr),
        .burst_hint(vif.burst_hint),
        .use_axi(vif.use_axi),
        .use_apb(vif.use_apb),
        .continuous_count(vif.continuous_count),
        .sequential_access(vif.sequential_access),
        .random_access(vif.random_access)
    );

    // 2. Parameterized SRAM
    sram_model #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH),
        .MEM_DEPTH(MEM_DEPTH)
    ) ram (
        .clk(vif.clk),
        .reset(vif.reset),
        .we(vif.write),
        .addr(vif.addr),
        .wdata(vif.wdata),
        .rdata(ram_rdata)
    );

    // 3. Parameterized Shared FIFO
    shared_fifo #(
        .DATA_WIDTH(DATA_WIDTH),
        .DEPTH(FIFO_DEPTH)
    ) fifo (
        .clk(vif.clk),
        .reset(vif.reset),
        .write_en(vif.write & vif.use_axi),
        .read_en(vif.read & vif.use_axi),
        .data_in(vif.wdata),
        .data_out(fifo_data),
        .full(fifo_full),
        .empty(fifo_empty)
    );

    // Connect SRAM read data to interface correctly
    always_comb begin
        vif.rdata = ram_rdata;
    end

    // Protocol signal generation based on classifier output
    // AXI Logic
    always_ff @(posedge vif.clk) begin
        if (vif.reset) begin
            awvalid <= 0;
            awready <= 0;
            wvalid  <= 0;
            wready  <= 0;
            bvalid  <= 0;
            arvalid <= 0;
            arready <= 0;
            rvalid  <= 0;
        end else begin
            if (current_proto == PROTO_AXI && vif.write) begin
                awvalid <= 1;
                awready <= 1;
                wvalid  <= 1;
                wready  <= 1;
                bvalid  <= 1;
            end else begin
                awvalid <= 0;
                awready <= 0;
                wvalid  <= 0;
                wready  <= 0;
                bvalid  <= 0;
            end

            if (current_proto == PROTO_AXI && vif.read) begin
                arvalid <= 1;
                arready <= 1;
                rvalid  <= 1;
            end else begin
                arvalid <= 0;
                arready <= 0;
                rvalid  <= 0;
            end
        end
    end

    // APB Logic
    always_ff @(posedge vif.clk) begin
        if (vif.reset) begin
            psel    <= 0;
            penable <= 0;
            pwrite  <= 0;
            pready  <= 0;
        end else begin
            if (current_proto == PROTO_APB && (vif.write || vif.read)) begin
                psel <= 1;
                pwrite <= vif.write;
                penable <= psel; // Delayed by 1 cycle for standard 2-cycle APB phase
                pready <= 1;
            end else begin
                psel <= 0;
                penable <= 0;
                pwrite <= 0;
                pready <= 0;
            end
        end
    end

endmodule

// ============================================================
// SYSTEMVERILOG ASSERTIONS (SVA)
// ============================================================
module assertions_bind (
    input clk,
    input reset,
    input psel,
    input penable,
    input pready,
    input awvalid,
    input awready,
    input use_axi,
    input use_apb,
    input fifo_full,
    input fifo_empty,
    input fifo_write_en,
    input fifo_read_en
);
    // --------------------------------------------------------
    // APB Protocol Assertions
    // --------------------------------------------------------

    // APB Protocol: penable should assert after psel
    property p_penable_implies_psel;
        @(posedge clk) disable iff (reset)
        penable |-> psel;
    endproperty
    assert property (p_penable_implies_psel) else $error("APB Protocol Error: penable asserted without psel");

    // APB Protocol: pready high during penable
    property p_pready_during_penable;
        @(posedge clk) disable iff (reset)
        penable |-> pready;
    endproperty
    assert property (p_pready_during_penable) else $error("APB Protocol Error: pready not asserted during penable");

    // --------------------------------------------------------
    // Protocol Mutual Exclusion
    // --------------------------------------------------------

    // Mutual Exclusion: use_axi and use_apb can never be high together
    property p_mutually_exclusive_protocols;
        @(posedge clk) disable iff (reset)
        not (use_axi && use_apb);
    endproperty
    assert property (p_mutually_exclusive_protocols) else $error("Arbiter Error: AXI and APB active simultaneously");

    // --------------------------------------------------------
    // AXI Protocol Assertions
    // --------------------------------------------------------

    // AXI Protocol: awvalid must stay high until awready
    property p_awvalid_to_awready;
        @(posedge clk) disable iff (reset)
        (awvalid && !awready) |=> awvalid;
    endproperty
    assert property (p_awvalid_to_awready) else $error("AXI Protocol Error: awvalid dropped before awready");

    // --------------------------------------------------------
    // FIFO Safety Assertions
    // --------------------------------------------------------

    // FIFO: never write when full (overflow protection)
    property p_fifo_no_overflow;
        @(posedge clk) disable iff (reset)
        fifo_write_en |-> !fifo_full;
    endproperty
    assert property (p_fifo_no_overflow) else $error("FIFO Error: Write attempted while FIFO is full");

    // FIFO: never read when empty (underflow protection)
    property p_fifo_no_underflow;
        @(posedge clk) disable iff (reset)
        fifo_read_en |-> !fifo_empty;
    endproperty
    assert property (p_fifo_no_underflow) else $error("FIFO Error: Read attempted while FIFO is empty");

    // --------------------------------------------------------
    // Protocol Liveness: at least one protocol must be active
    // --------------------------------------------------------
    property p_protocol_liveness;
        @(posedge clk) disable iff (reset)
        (use_axi || use_apb);
    endproperty
    assert property (p_protocol_liveness) else $warning("Warning: No protocol active — system idle");

endmodule

bind top_memory_system assertions_bind sv_assertions (
    .clk(vif.clk),
    .reset(vif.reset),
    .psel(psel),
    .penable(penable),
    .pready(pready),
    .awvalid(awvalid),
    .awready(awready),
    .use_axi(vif.use_axi),
    .use_apb(vif.use_apb),
    .fifo_full(fifo_full),
    .fifo_empty(fifo_empty),
    .fifo_write_en(vif.write & vif.use_axi),
    .fifo_read_en(vif.read & vif.use_axi)
);